export { Heading, type HeadingProps } from './Heading'
export { Input, type InputProps } from './Input'
export { Link, type LinkProps } from './Link'
export { Screen, type ScreenProps } from './Screen'
export { Text, type TextProps } from './Text'
